### PR TITLE
Bugfix/reduce lag

### LINKED ISSUE #330: [BUGFIX] Fix the lag issues

### PR DESCRIPTION
**Pull request by yzueger**
Closes #330 

This reduces most of the remaining lag by
- Using the ioDispatcher in the Firebase connections
- Disabling the navigation animations that slow things down

### CODE REVIEW

**Review by aymanbakiri — APPROVED** [review]
Thanks for making these changes.
 Using the ioDispatcher in the Firebase connections and disabling the navigation animations have significantly reduced the remaining lag. 
Your work has really improved things
I think it is ready to merge

**Review by mbouaissi — CHANGES_REQUESTED** [review]
There is weird thing happening when i switch screens,

**Comment by mbouaissi** [comment]
Uploading Screen_Recording_20240523-200730_wanderwave.mp4…

**Comment by mbouaissi** [comment]
https://github.com/G12-Wanderwave/Wanderwave/assets/112695678/b5728333-273a-49bc-ae51-808d2dc6268d

**Pull request merged**
