### PR TITLE
Feature/beacon screen/merge with main

### PR DESCRIPTION
**Pull request by joriba**
Just merge main into the feature branch and fix all the merge conflicts

### CODE REVIEW

**Review by mbouaissi — DISMISSED** [review]
it has already be reviewed in previous PR so lgtm :+1:

**Comment by mbouaissi** [comment]
lgtm 2

**Comment by joriba** [comment]
@mbouaissi you need to Approve as well so I can merge it :)

**Review by aymanbakiri — APPROVED** [review]

**Comment by aymanbakiri** [comment]
LGTM

**Pull request merged**
